---
name: Excercise2
on:
    pull_request:
        branches:
            -dev
jobs:
    excercise2:
        runs-on: ubuntu-latest
        steps:
            - name: pull_request
              run : "echo pull_request created."